name: anomaly-classifier
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip:
    - setuptools==69.5.1
    - lightgbm==4.3.0
    - scikit-learn==1.4.0
    - pandas==2.2.0
    - numpy==1.26.0
    - mlflow==2.10.0
    - protobuf==4.25.3
    - azureml-mlflow==1.56.0
    - azureml-inference-server-http
